wrong paths
Add container jobs back in

Fix cgroups-rs

diff --git a/.github/workflows/030-ubuntu-aurae-builder-image-ubuntu-docker-build.yml b/.github/workflows/030-ubuntu-aurae-builder-image-ubuntu-docker-build.yml
--- a/.github/workflows/030-ubuntu-aurae-builder-image-ubuntu-docker-build.yml
+++ b/.github/workflows/030-ubuntu-aurae-builder-image-ubuntu-docker-build.yml
@@ -27,54 +27,72 @@
 #   limitations under the License.                                             #
 #                                                                              #
 # ---------------------------------------------------------------------------- #
+#
+name: "Aurae Builder Image (030) [ubuntu:latest]"
+on: [workflow_call]
+permissions:
+ contents: read
+ packages: write
+env:
+ CARGO_TERM_COLOR: always
+ CACHE_VERSION: v0
+jobs:
+ build-container:
+   name: Build container image
+   runs-on: ubuntu-latest
+   concurrency:
+     group: ${{ format('{0}-{1}', github.ref, github.job) }}
+   outputs:
+       tag: ${{ steps.image-tag.outputs.tag}}
+   steps:
+     - uses: actions/checkout@v3
+       with:
+         fetch-depth: 0
+     - id: image-tag
+       run: |
+         echo "tag=${{ hashFiles('**images/Dockerfile.build') }}" >> $GITHUB_OUTPUT
 
-[package]
-name = "auraed"
-version = "0.1.0"
-edition = "2021"
-authors = ["The Aurae Authors", "Kris Nóva <kris@nivenly.com>"]
-license = "Apache-2.0"
+     - name: Check if container build needs to run
+       uses: actions/cache@v3
+       id: check-change
+       with:
+         path: |
+           images/Dockerfile.build
+         key: build-image-marker-${{ runner.os }}-${{ hashFiles('**images/Dockerfile.build') }}-${{env.CACHE_VERSION}}
 
-[[bin]]
-name = "auraed"
-path = "src/bin/main.rs"
+     - name: Set up container buildx
+       if: steps.check-change.outputs.cache-hit != 'true'
+       uses: docker/setup-buildx-action@v2
+       with:
+         install: true
 
-[dependencies]
-anyhow = { workspace = true }
-aurae-client = { workspace = true }
-aurae-proto = { workspace = true }
-clap = { version = "3.1.20", features = ["derive"] }
-clone3 = "0.2.3"
-fancy-regex = { workspace = true }
-futures = "0.3.23"
-ipnetwork = "0.20.0"
-iter_tools = "0.1.4"
-libc = "0.2" # TODO: Nix comes with libc, can we rely on that?
-lazy_static = { workspace = true }
-#libcontainer = { git = "https://github.com/krisnova/youki", branch = "musl-build-6.1.1-kernel" }
-liboci-cli = "0.0.4"
-log = "0.4.17"
-netlink-packet-route = "0.13.0" # Used for netlink_packet_route::rtnl::address::nlas definition
-nix = { version = "0.26.1", features = ["sched"] }
-ocipkg = "0.2.8"
-procfs = "0.14.2"
-rtnetlink = "0.11.0"
-simplelog = "0.12.0"
-thiserror = { workspace = true }
-tokio = { workspace = true, features = ["macros", "fs", "rt-multi-thread", "sync", "signal", "process"] }
-tokio-stream = { version = "0.1", features = ["net", "sync"] }
-tonic = { workspace = true, features = ["tls"] }
-tracing = { workspace = true, features = ["log"] }
-tracing-log = "0.1"
-tracing-subscriber = { version = "0.3", features = ["env-filter", "registry"] }
-tracing-rfc-5424 = { version = "0.1.0" }  # syslog tracing
-uuid = { version = "1.2.2", features = ["v4"] }
-validation = { path = "../crates/validation", features = ["regex", "tonic"] }
-validation_macros = { path = "../crates/validation/macros" }
-walkdir = "2"
-multi_log = "0.1.2"
-cgroups-rs = "0.3.0"
+     - name: Login to Github Container Registry
+       if: steps.check-change.outputs.cache-hit != 'true'
+       uses: docker/login-action@v2
+       with:
+         registry: ghcr.io
+         username:  ${{ github.actor }}
+         password:  ${{ secrets.GITHUB_TOKEN }}
 
-[dev-dependencies]
-simple_test_case = "1.1.0"
+     - name: Create Docker Build Image
+       id: build-and-push
+       if: steps.check-change.outputs.cache-hit != 'true' && github.event.pull_request.head.repo.full_name == github.repository
+       uses: docker/build-push-action@v2
+       timeout-minutes: 15
+       with:
+         context: .
+         file: images/Dockerfile.build
+         push: true
+         build-args: CACHE_VERSION=${{env.CACHE_VERSION}}
+         tags: ghcr.io/${{ github.repository }}/aurae-builder:latest,ghcr.io/${{ github.repository }}/aurae-builder:${{ steps.image-tag.outputs.tag}}
+         cache-from: type=gha
+         cache-to: type=gha,mode=max
 
+     - name: Fail if fork is changing Dockerfile
+       id: build
+       if: github.event.pull_request.head.repo.full_name != github.repository
+       run: |
+         ## If the fork has changed the Dockerfile, we need to fail the pipeline.
+         ## This is to prevent a case where a forked repo could expect changes in the Dockerfile
+         ## to be used in the build process.
+         git diff --quiet HEAD origin/main -- images/Dockerfile.build || exit 1
